name: HTS Version Checker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "HTS environment (mirror | prerelease)"
        required: true
        default: mirror

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run version script
        run: |
          chmod +x get_version.sh
          ./get_version.sh "${{ github.event.inputs.environment }}"
